### ISSUE TITLE
TestAMFVFW version rejected in Sony Vegas

### ISSUE THREAD

**Issue by Prehistoricman** [jackun/openencodevfw#27]
http://prntscr.com/84d697
I've fiddled with every property in the project settings and VFW I can see, this error pops up. As far as I can tell, it doesn't matter what the project is. I've created a dummy project with one video file and one sound track, and this still occurs.
Is there any change that would affect how the codec would communicate with programs using it?

Sony Vegas Pro 13.0 on Windows 7 x64 with the Radeon HD 7870 XT.

Edit: I should mention again that I'm RENDERING from Vegas with your codec, not importing videos recorded with your codec. Just to clarify it's not like other Vegas issues with importing.

**Comment by ari2k5** [comment]
Could you share your project settings from Vegas like resolution/framerate/etc

**Comment by Prehistoricman** [comment]
Using Pro 13.0 build 453

These are screenshots of the project properties dialog:
http://prntscr.com/8qhtsk
http://prntscr.com/8qhu1j
Rending settings:
http://prntscr.com/8qhugy
http://prntscr.com/8qhumn

**Comment by jackun** [comment]
Vegas is probably feeding it data in unsupported pixel format or width/height is not divisable by 2. I don't remember if there was a place to force it somewhere. Currently supported is NV12 (fastest), YV12, RGBx (has to flip the pixels because DIB is upside-down, ugh).

Enable logging and there should be a line like:

     Compression query: 32 0 1920x1080

32 is bits per pixel, 0 is compression ([FOURCC](http://www.fourcc.org/codecs.php), 0 means none a.k.a raw RGB). Otherwise it needs more detective work.

**Comment by Prehistoricman** [comment]
You must have fixed it since I noticed a problem. I'd been dual booting with old drivers to use the non-AMF version and didn't update until I couldn't find the logging file (even looked for it being written in Resource Monitor, got nothing). Even works when the project is set to 8 bit pixel format.

Thanks for your great support and code!
